import { KeepNote, MealItem, WorkoutSession, MacroTargets } from '../types';

export function createGroceryKeepNote(meals: MealItem[]): KeepNote {
  const allIngredients = new Set<string>();
  meals.forEach((meal) => {
    meal.ingredients.forEach((ing) => allIngredients.add(ing.trim()));
  });

  const items = Array.from(allIngredients).map((ing) => ({
    text: ing,
    checked: false,
  }));

  const plainContent = `🛒 WEEKLY WEIGHT LOSS GROCERY CHECKLIST
Generated by AI Weight Loss Coach
------------------------------------------
${items.map((i) => `☐ ${i.text}`).join('\n')}

💡 Tip: High-volume, high-fiber, and high-protein foods keep you in a sustainable caloric deficit.`;

  return {
    id: `keep-grocery-${Date.now()}`,
    title: '🛒 Weekly Healthy Grocery Checklist',
    category: 'grocery',
    items,
    plainContent,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString(),
    tags: ['Groceries', 'Nutrition', 'Meal Prep', 'Keep Ready'],
  };
}

export function createMealPlanKeepNote(meals: MealItem[], macros: MacroTargets): KeepNote {
  const mealSections = meals.map((m) => {
    return `🍽️ ${m.type.toUpperCase()}: ${m.name}
Calories: ${m.calories} kcal | Protein: ${m.protein}g | Carbs: ${m.carbs}g | Fat: ${m.fat}g
Ingredients: ${m.ingredients.join(', ')}
Prep Time: ${m.prepTimeMinutes} mins
`;
  }).join('\n------------------------------------------\n');

  const items = meals.map((m) => ({
    text: `${m.type.toUpperCase()}: ${m.name} (${m.calories} kcal, ${m.protein}g Protein)`,
    checked: false,
  }));

  const plainContent = `🥗 DAILY NUTRITION & MEAL PLAN
Daily Calorie Target: ${macros.calories} kcal | Protein: ${macros.proteinGrams}g | Carbs: ${macros.carbsGrams}g | Fat: ${macros.fatGrams}g
------------------------------------------
${mealSections}
------------------------------------------
💧 Water Target: 3.0+ Liters | Fiber: 30g+`;

  return {
    id: `keep-meal-${Date.now()}`,
    title: '🥗 Daily Meal & Macro Nutrition Note',
    category: 'meal_plan',
    items,
    plainContent,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString(),
    tags: ['Meal Plan', 'Macros', 'Diet', 'Healthy Eating'],
  };
}

export function createWorkoutRoutineKeepNote(workouts: WorkoutSession[]): KeepNote {
  const items: { text: string; checked: boolean }[] = [];
  workouts.forEach((w) => {
    items.push({ text: `[${w.dayOfWeek}] ${w.title} (${w.durationMinutes}m)`, checked: false });
  });

  const fullText = workouts.map((w) => {
    const exs = w.exercises.map((e) => `  • ${e.name}: ${e.sets}x${e.repsOrDuration} (Rest: ${e.restSeconds}s)`).join('\n');
    return `🏋️ ${w.dayOfWeek.toUpperCase()} - ${w.title} (${w.durationMinutes}m, ~${w.estimatedCaloriesBurn} kcal)\n${exs}`;
  }).join('\n\n');

  return {
    id: `keep-workout-${Date.now()}`,
    title: '🏋️ Weekly Training & Recovery Split',
    category: 'workout',
    items,
    plainContent: `🏋️ WEEKLY WORKOUT & PROGRESSION PLAN\n------------------------------------------\n${fullText}`,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString(),
    tags: ['Workouts', 'Hypertrophy', 'Cardio', 'Training'],
  };
}

export function createHabitsKeepNote(): KeepNote {
  const habitItems = [
    { text: 'Drink 500ml water immediately upon waking up', checked: false },
    { text: 'Eat 30g+ high-quality protein at breakfast for satiety', checked: false },
    { text: 'Complete scheduled workout or 8,000 - 10,000 steps NEAT', checked: false },
    { text: 'Pre-load with 500ml water 20 mins before dinner', checked: false },
    { text: 'No screens 45 mins before bedtime; aim for 7.5 - 8.5 hours sleep', checked: false },
    { text: 'Log daily morning weight and celebrate consistency', checked: false },
  ];

  return {
    id: `keep-habits-${Date.now()}`,
    title: '💡 Daily Fat Loss Non-Negotiable Habits',
    category: 'habit_tracker',
    items: habitItems,
    plainContent: `💡 DAILY FAT LOSS NON-NEGOTIABLE HABITS\n------------------------------------------\n${habitItems.map((h) => `☐ ${h.text}`).join('\n')}`,
    createdDate: new Date().toISOString(),
    updatedDate: new Date().toISOString(),
    tags: ['Habits', 'Psychology', 'Consistency', 'Daily Checklist'],
  };
}
